"""Initial migration with JWT models

Revision ID: 1a5f0802bcc9
Revises: 
Create Date: 2025-09-18 13:56:24.277959

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a5f0802bcc9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('customers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phone_number', sa.String(length=15), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone_number')
    )
    op.create_table('cars',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('make', sa.String(length=80), nullable=False),
    sa.Column('model', sa.String(length=80), nullable=False),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('car_services',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('car_id', sa.Integer(), nullable=False),
    sa.Column('engine_oil', sa.Boolean(), nullable=True),
    sa.Column('air_filter', sa.Boolean(), nullable=True),
    sa.Column('oil_filter', sa.Boolean(), nullable=True),
    sa.Column('gear_oil', sa.Boolean(), nullable=True),
    sa.Column('power_steering_oil', sa.Boolean(), nullable=True),
    sa.Column('fuel_filter', sa.Boolean(), nullable=True),
    sa.Column('washer_fluid', sa.Boolean(), nullable=True),
    sa.Column('coolant', sa.Boolean(), nullable=True),
    sa.Column('mileage', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['car_id'], ['cars.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('car_services')
    op.drop_table('cars')
    op.drop_table('customers')
    op.drop_table('admins')
    # ### end Alembic commands ###
